### ISSUE TITLE
3.99测试版两个问题和一个建议

### ISSUE THREAD

**Issue by rtxyd** [bobcao3/Wisdom-Shaders#17]
1、在特定的角度看冰与火之歌的龙眼睛会丢失材质，变成两个黑色的「」这种形状的。
2、火把在半砖下面的时候晚上会隔墙照亮那块半砖以及半砖周围的方块。
另外下雨的时候所有表面（包括生物，比如冰与火之歌的5级龙，飞起来贼壮观）都有反光，怎么说呢，建议改一下。

**Comment by bobcao3** [comment]
I'm not sure about the first one, seems like a problem with the mods / resource packs in use
The second issue is caused by Minecraft itself, the shaders can't do anything
The rain reflection is a design choice. Unless LabPBR resource packs with proper surface porosity textures have been widely adopted, this is going to be there for future versions
